### ISSUE TITLE
comprehensive tests for `mintx`

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/mint-client#33]
bash script/Dockerfile. use these to finish #23

**Comment by zramsay** [comment]
update bash files to append properly 
http://stackoverflow.com/questions/4181703/how-can-i-concatenate-string-variables-in-bash

**Comment by zramsay** [comment]
waiting on fixes to `mintx unbond`

**Comment by zramsay** [comment]
unblocked by ^.

**Comment by alexklho** [comment]
I have this error when calling `mintx unbond` in the chain container.

```
bash-4.3# mintx unbond
panic: shorthand redefinition

goroutine 1 [running]:
panic(0x7fdda0, 0xc820122340)
	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/eris-ltd/mint-client/Godeps/_workspace/src/github.com/spf13/pflag.(*FlagSet).AddFlag(0xc820128200, 0xc820077300)
	/go/src/github.com/eris-ltd/mint-client/Godeps/_workspace/src/github.com/spf13/pflag/flag.go:506 +0xcae
github.com/eris-ltd/mint-client/Godeps/_workspace/src/github.com/spf13/cobra.(*Command).mergePersistentFlags.func1(0xc820077300)
	/go/src/github.com/eris-ltd/mint-client/Godeps/_workspace/src/github.com/spf13/cobra/command.go:999 +0x31
github.com/eris-ltd/mint-client/Godeps/_workspace/src/github.com/spf13/pflag.(*FlagSet).VisitAll(0xc820077280, 0xc820045bf8)
	/go/src/github.com/eris-ltd/mint-client/Godeps/_workspace/src/github.com/spf13/pflag/flag.go:223 +0x85
github.com/eris-ltd/mint-client/Godeps/_workspace/src/github.com/spf13/cobra.(*Command).mergePersistentFlags(0xc8201241a0)
	/go/src/github.com/eris-ltd/mint-client/Godeps/_workspace/src/github.com/spf13/cobra/command.go:1002 +0x237
github.com/eris-ltd/mint-client/Godeps/_workspace/src/github.com/spf13/cobra.(*Command).ParseFlags(0xc8201241a0, 0xc312f8, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/eris-ltd/mint-client/Godeps/_workspace/src/github.com/spf13/cobra/command.go:979 +0x2f
github.com/eris-ltd/mint-client/Godeps/_workspace/src/github.com/spf13/cobra.(*Command).execute(0xc8201241a0, 0xc312f8, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/eris-ltd/mint-client/Godeps/_workspace/src/github.com/spf13/cobra/command.go:454 +0x258
github.com/eris-ltd/mint-client/Godeps/_workspace/src/github.com/spf13/cobra.(*Command).Execute(0xc820124680, 0x0, 0x0)
	/go/src/github.com/eris-ltd/mint-client/Godeps/_workspace/src/github.com/spf13/cobra/command.go:551 +0x46a
main.main()
	/go/src/github.com/eris-ltd/mint-client/mintx/main.go:183 +0x1492
```

Same for `mintx name`, `mintx call`, `mintx rebond` and `mintx permission`. Guess it is because of collision with the flags `addr` and `d` of the root command `mintx`.

How can I test and verify?

**Comment by zramsay** [comment]
hi @alexklho thanks for the bug report.
what version of `eris-cli` are you on? this should've been fixed in #66

**Comment by alexklho** [comment]
I'm installing eris through `go get`, which is currently using `eris-cli` version 0.11.4.
